name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Docker image tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rvc:${{ env.IMAGE_TAG }}
    - name: Save the Docker image
      run: docker save rvc:${{ env.IMAGE_TAG }} -o RVC.tar
    - name: Commit and push version update
      uses: EndBug/add-and-commit@v9
      with:
        add: '.version'
        message: 'TEST'
        author_name: 'github-actions'
        author_email: 'github-actions@github.com'
    - name: Upload Docker image tar file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: RVC.tar

